#!/bin/bash -e

export TALON_HOME=$HOME/gopath/src/gophergo.org/p/talon/
mkdir -p $TALON_HOME
cp -R $HOME/gopath/src/github.com/hyper-carrot/talon/* $TALON_HOME
cd  $TALON_HOME
echo The workspace: $TALON_HOME

go test -v ./base
go test -v ./logging
go test -v ./middleware
go test -v ./analyzer
go test -v ./downloader
go test -v ./itempipeline
go test -v ./scheduler
go test -v ./tool/cookie
